### ISSUE TITLE
unable to execute flash loan

### ISSUE THREAD

**Issue by BigGod12** [balancer/balancer-subgraph-v2#544]
hello, i need some help please, i`m just getting started with balance flash loan, i`m a lil familiar with aave flash loan, but when i compile and deployed this code just to test the flow of the flash loan without conducting any arbitrage or swap, though i removed the userData param, yet after inputing the address from one of the pool and the amount, the transact is not working, i`m on sepolia testnet, do i need another address to use the testnet or something is wrong with my code, thank you

pragma solidity ^0.7.0;

import "@balancer-labs/v2-interfaces/contracts/vault/IVault.sol";
import "@balancer-labs/v2-interfaces/contracts/vault/IFlashLoanRecipient.sol";

contract FlashLoanRecipient is IFlashLoanRecipient {
    IVault private constant vault = IVault(0xBA12222222228d8Ba445958a75a0704d566BF2C8);

    function makeFlashLoan(
        IERC20[] memory tokens,
        uint256[] memory amounts
    ) external {
      vault.flashLoan(this, tokens, amounts, "");
    }

    function receiveFlashLoan(
        IERC20[] memory tokens,
        uint256[] memory amounts,
        uint256[] memory feeAmounts,
        bytes memory userData
    ) external override {
        require(msg.sender == address(vault), "Flash loan can only be called by the vault");

        // Repay the flash loan
        for (uint256 i = 0; i < tokens.length; i++) {
            IERC20 token = tokens[i];
            uint256 repayAmount = amounts[i] + feeAmounts[i];
            token.transfer(address(vault), repayAmount);
        }
    }
}

**Comment by mendesfabio** [comment]
hey @BigGod12 - I'm sorry but I don't know how to answer this question, you should join our [Discord](https://discord.balancer.fi/) and ask it on #dev channel. Give as much details as possible there and someone may be able to help. I'll close this issue since it's not related to Subgraph, thanks for understanding!
