### ISSUE TITLE
Where is the pool-management-v2 repo and core submodule ?

### ISSUE THREAD

**Issue by hwnahm** [balancer/balancer-subgraph-v2#561]
I can't find the repo. Is it private ?

**Comment by mendesfabio** [comment]
hey -- [`pool-management`](https://github.com/balancer/pool-management) is the repository of our V1 app, and the V2 is located at [`frontend-v2`](https://github.com/balancer/frontend-v2). If you have further questions, please join [Balancer Discord](https://discord.balancer.fi/) and our devs will be able to help you!
