### ISSUE TITLE
fix: weighted pool comes back as yield fee exempt

### ISSUE THREAD

**Issue by gosuto-inzasheru** [balancer/balancer-subgraph-v2#592]
it is not clear to us what is happening here:

https://github.com/balancer/balancer-subgraph-v2/blob/1d333056e4e4eab900e6ce0772bc1d2ca82eff7b/src/mappings/helpers/misc.ts#L208-L211

use case is this pool `0xff42a9af956617e4c3532ef2fc7567465efe4909000200000000000000000672`, for which the following query comes back with at least one `true`:
```
{
  poolTokens(where: { poolId: "0xff42a9af956617e4c3532ef2fc7567465efe4909000200000000000000000672" }) {
    poolId {
      address
    }
    id
    isExemptFromYieldProtocolFee
  }
}
```

expectation however is that weighted pools cannot ever be yield fee exempt?

**Comment by mendesfabio** [comment]
I assume we're talking about this [pool](https://api.thegraph.com/subgraphs/name/balancer-labs/balancer-v2/graphql?query=%7B%0A%09pool(%0A++++id:+%220xff42a9af956617e4c3532ef2fc7567465efe4909000200000000000000000672%22%0A++)+%7B%0A%09++id%0A++++tokens+%7B%0A++++++symbol%0A++++++address%0A++++++isExemptFromYieldProtocolFee%0A++++%7D%0A++++priceRateProviders+%7B%0A++++++address%0A++++%7D%0A%09%7D%0A%7D%0A) right?

> expectation however is that weighted pools cannot ever be yield fee exempt?

if a pool token (even yield-bearing) has no rate-provider it's going to be yield fee exempt.
